sudo: required
language: go
services:
- docker
go:
- 1.10.x
go_import_path: github.com/heroku/tatara
install:
- mkdir -p $GOPATH/bin
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- dep ensure
- go get github.com/buildpack/forge
- cd $GOPATH/src/github.com/buildpack/forge
- git remote add fork https://github.com/jkutner/forge
- git fetch fork
- git reset --hard fork/refactor-jkutner
- dep ensure
- cd -
before_script:
- export VERSION="$(cat VERSION)"
script:
- bin/test
- bin/build $TARGET_OS
- ls out/
matrix:
  include:
  - os: linux
    env:
      TARGET_OS: windows
      OUTPUT_EXT: windows.exe
  - os: linux
    env:
      TARGET_OS: linux
      OUTPUT_EXT: linux
  - os: osx
    env:
      TARGET_OS: darwin
      OUTPUT_EXT: macos
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "out/tatara-${VERSION}-${OUTPUT_EXT}"
  skip_cleanup: true
  on:
    tags: true
