sudo: required
language: go
services:
- docker
go:
- 1.10.x
install:
- set -e
- curl -fsSLo "$GOPATH/bin/dep" "https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64"
- chmod +x "$GOPATH/bin/dep"
- dep ensure
before_script:
- export VERSION="$(cat VERSION)"
script:
- test -z "$(bin/format | tee >(cat >&2))"
- bin/test
- bin/build
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "out/heroku-local-${VERSION}-macos"
    - "out/heroku-local-${VERSION}-linux"
    - "out/heroku-local-${VERSION}-windows"
  skip_cleanup: true
  on:
    tags: true
