sudo: required
language: go
services:
- docker
go:
- 1.10.x
go_import_path: github.com/heroku/heroku-local-build
install:
- set -e
- curl -fsSLo "$GOPATH/bin/dep" "https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64"
- chmod +x "$GOPATH/bin/dep"
- dep ensure
- go get github.com/sclevine/forge
- ( cd "$GOPATH/src/github.com/sclevine/forge" && git remote add fork https://github.com/jkutner/forge )
- ( cd "$GOPATH/src/github.com/sclevine/forge" && git reset --hard fork/master )
- ( cd "$GOPATH/src/github.com/sclevine/forge" && git fetch fork )
- ( cd "$GOPATH/src/github.com/sclevine/forge" && dep ensure )
before_script:
- export VERSION="$(cat VERSION)"
script:
- bin/test
- bin/build
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "out/heroku-local-${VERSION}-macos"
    - "out/heroku-local-${VERSION}-linux"
    - "out/heroku-local-${VERSION}-windows"
  skip_cleanup: true
  on:
    tags: true
