sudo: required
language: go
services:
- docker
go:
- 1.11.x
go_import_path: github.com/heroku/tatara
install:
- go mod vendor
before_script:
- export VERSION="$(cat VERSION)"
script:
- bin/test
- bin/build $TARGET_OS
- ls out/
matrix:
  include:
  - os: linux
    env:
      GO111MODULE: "on"
      TARGET_OS: windows
      OUTPUT_EXT: windows.exe
  - os: linux
    env:
      GO111MODULE: "on"
      TARGET_OS: linux
      OUTPUT_EXT: linux
  - os: osx
    env:
      GO111MODULE: "on"
      TARGET_OS: darwin
      OUTPUT_EXT: macos
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "out/tatara-${VERSION}-${OUTPUT_EXT}"
  skip_cleanup: true
  on:
    tags: true
