ignored = [
  "github.com/buildpack/forge",
  "github.com/buildpack/forge/*",
]

# App

[[constraint]]
  name = "github.com/fsnotify/fsevents"
  branch = "master"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  branch = "master"

[[constraint]]
  name = "github.com/sabhiram/go-gitignore"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
